---
- name: deploy any jar file
  ansible.builtin.get_url:
    url: "{{ deploy_url }}"
    dest: "{{ tomcat_latest }}/webapps/{{deploy_file_name}}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0777'  
    url_username: "{{ jfrog_user }}" 
    url_password: "{{ jfrog_passwd }}" 
  notify:
    - reload the daemon, enable and start the tomcat service
        
